global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"] # scrape Prometheus exporter
  - job_name: "otel-collector-internal"
    static_configs:
      - targets: ["otel-collector:8888"] # scrape internal metrics
