model_list:
  - model_name: gemma3-27b # or tinyllama if you're on a Mac and want to quickly test
    litellm_params:
      model: ollama/gemma3:27b # or ollama/tinyllama if you're on a Mac and want to quickly test
      api_base: http://host.docker.internal:11434

litellm_settings:
  callbacks: ["prometheus"]